name: Publish Docker image
on:
  push:
    branches:
      - main
    tags:
      - "*"
  pull_request:
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4.0.1
        with:
          images: ghcr.io/frezbo/docker-actions-test
          flavor: |
            latest=false
          tags: |
            type=sha
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1.2.0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1.7.0
      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_ACCESS_TOKEN }}
      - name: Build and push
        uses: docker/bake-action@v2.0.0
        with:
          files: |
            ./docker-bake.hcl
            ${{ steps.meta.outputs.bake-file }}
          targets: build
          pull: true
          load: false
          push: ${{ github.event_name != 'pull_request' }}
